# Generated by Django 4.1 on 2022-10-08 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre usuario')),
                ('apellido', models.CharField(max_length=50, verbose_name='Apellido usuario')),
                ('nombreDeUsuario', models.CharField(max_length=50, verbose_name='Nombre de usuario')),
            ],
        ),
    ]
