# Generated by Django 4.1 on 2022-10-08 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startprueba', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='clientes',
            fields=[
                ('cedula', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='CEDULA')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre cliente')),
                ('apellido', models.CharField(max_length=50, verbose_name='Apellido cliente')),
                ('correo_electronico', models.CharField(max_length=50, verbose_name='correo electronico cliente')),
                ('direccion', models.CharField(max_length=50, verbose_name='direccion  del cliente ')),
            ],
        ),
        migrations.CreateModel(
            name='pedidos',
            fields=[
                ('nombre_cliente', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='CEDULA')),
                ('direccion', models.CharField(max_length=50, verbose_name='Direccion cliente')),
                ('direccion_punto', models.CharField(max_length=50, verbose_name='Dirrecion punto')),
                ('barrio', models.CharField(max_length=50, verbose_name='barrio del cliente')),
                ('numero_contacto', models.CharField(max_length=50, verbose_name='numero de contacto cliente')),
                ('guia_pedido', models.CharField(max_length=50, verbose_name='guia pedido cliente')),
            ],
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
