# Generated by Django 4.1 on 2022-10-08 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startprueba', '0002_clientes_pedidos_delete_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='cargo',
            fields=[
                ('gerente', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='gerente')),
                ('gerente_marketing', models.CharField(max_length=50, verbose_name='gerente marketing')),
                ('administrador', models.CharField(max_length=50, verbose_name='administrador')),
                ('gerente_financiero', models.CharField(max_length=50, verbose_name='gerente financiero')),
            ],
        ),
        migrations.CreateModel(
            name='factura1',
            fields=[
                ('nombre_cliente', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='Nombre cliente')),
                ('direccion', models.CharField(max_length=50, verbose_name='Direccion cliente')),
                ('barrio', models.CharField(max_length=50, verbose_name='barrio del cliente')),
                ('numero_de_contacto', models.CharField(max_length=50, verbose_name='numero de contacto cliente')),
                ('forma_de_pago', models.CharField(max_length=50, verbose_name='Forma de pago cliente')),
                ('codigo_producto', models.CharField(max_length=50, verbose_name='codigo del producto')),
                ('metodo_de_pago', models.CharField(max_length=50, verbose_name='metodo de pago del cliente ')),
                ('valor_a_pagar', models.CharField(max_length=50, verbose_name='valor a pagar')),
            ],
        ),
        migrations.CreateModel(
            name='factura2',
            fields=[
                ('cantidad_productos', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='Cantidad productos')),
                ('codigo', models.CharField(max_length=50, verbose_name='codigo')),
                ('sub_total', models.CharField(max_length=50, verbose_name='subtotal')),
            ],
        ),
        migrations.CreateModel(
            name='pagos',
            fields=[
                ('sueldo', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='sueldo')),
                ('prima', models.CharField(max_length=50, verbose_name='prima')),
                ('vacaciones', models.CharField(max_length=50, verbose_name='vacaciones')),
                ('prestaciones_sociales', models.CharField(max_length=50, verbose_name='prestaciones sociales')),
                ('bonificaciones_extra', models.CharField(max_length=50, verbose_name='bonificaciones')),
                ('subsidio', models.CharField(max_length=50, verbose_name='subsidio')),
                ('descuentos', models.CharField(max_length=50, verbose_name='descuentos')),
                ('seguros', models.CharField(max_length=50, verbose_name='seguros ')),
            ],
        ),
        migrations.CreateModel(
            name='productos',
            fields=[
                ('catalogo', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='catalogo')),
                ('precios', models.CharField(max_length=50, verbose_name='precios')),
                ('fecha_creacion', models.CharField(max_length=50, verbose_name='fecha creacion producto')),
                ('material', models.CharField(max_length=50, verbose_name='material del producto')),
            ],
        ),
        migrations.CreateModel(
            name='provedores',
            fields=[
                ('maderas_SAS', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='empresa maderas sas ')),
                ('administrador', models.CharField(max_length=50, verbose_name='unidades administrador')),
                ('socios', models.CharField(max_length=50, verbose_name='socios')),
                ('fabricantes', models.CharField(max_length=50, verbose_name=' fabricantes')),
            ],
        ),
        migrations.CreateModel(
            name='puntosdeventa',
            fields=[
                ('cardinalidad', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='cardinalidad')),
                ('ubicacion', models.CharField(max_length=50, verbose_name='ubicacion')),
                ('direccion_punto', models.CharField(max_length=50, verbose_name='direccion punto')),
            ],
        ),
        migrations.CreateModel(
            name='stock',
            fields=[
                ('disponibilidad_productos', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='disponibilidad de los productos ')),
                ('unidades_almacenadas', models.CharField(max_length=50, verbose_name='unidades almacenadas')),
                ('actualizacion_de_ventas', models.CharField(max_length=50, verbose_name='actualizacion de ventas')),
                ('existencias_productos', models.CharField(max_length=50, verbose_name='existencias productos')),
            ],
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='nombre_cliente',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='nombre'),
        ),
    ]
